### ISSUE TITLE
Ekran görüntüsü

### ISSUE THREAD

**Issue by ttuygun** [okan/kerb#6]
Merhaba Okan. 24 saatte öğrenip yazdığınız için ayrıca bir ilgimi çekti kütüphane. Ekran görüntülerini de eklerseniz birebir görmek adına çok iyi olur.

Sevgiler.

**Comment by okan** [comment]
merhaba @ttuygun,
youtube'a bir video yükledim. şuradan erişebilirsin:
https://www.youtube.com/watch?v=S3RBnH7Z4Z8

ilgin için çok teşekkürler.
